<!-- //module/SanAuth/view/san-auth/success/index.phtml -->
<p /> NOn c'è bisogno di questa pagina, c'è redirect automatico nel controller AuthController
<h1>Login Effettuato</h1>
<p />
<p />
<p />
<p />
<p />
<p> Login effettuato, stai per essere indirizzato alla PRIMA NOTA </p>

<meta http-equiv="Refresh" content="5; url=/ZendAuth/public/album" />


<!--<p />
<p />
Login effettuato con successo.
<br />
<p>

</p>
<p>
 <a href="<?php echo $this->url('album', array('action'=>'index')); ?>">VAI ALLA PRIMA NOTA</a> 
</p>
<br />
 <a href="<?php echo $this->url('login/process', array('action'=>'logout')); ?>">Logout</a>
-->


